In [2]:
import pandas as pd
import csv

In [3]:
# Reading original .csv
df = pd.read_csv('../WikiArtClean.csv')
df = df.drop(columns=['Image URL', 'Painting Info URL', 'Artist Info URL'])
# List of all columns
columns = list(df.columns)
# List of mood attributes
moods = columns[8:]

In [4]:
# Getting all different styles
styles = []

for index, row in df.iterrows():
    if row[0] not in styles:
        styles.append(row[0])

In [5]:
# Creating dataframes for each style

styleFrames = [];

for style in styles:
    newDf = df.loc[df['Style'] == style]
    styleFrames.append(newDf)

In [18]:
# CSVs for average ratings of each Artist per style

allAverages = []

for i in range(len(styles)):
    frame = styleFrames[i].groupby(['Artist']).mean()
    frame = frame.drop(columns=['Year'])
    frame = frame.sort_values(by=['Mean rating'], ascending=False)
    topN = 15;
    frame = frame.head(topN)
    allAverages.append(frame)
    fileName = styles[i] + '_top15Artists.csv'
#     frame.to_csv(fileName)

allAverages[1]

,Mean rating,Agreeableness,Anger,Anticipation,Arrogance,Disagreeableness,Disgust,Fear,Gratitude,Happiness,...,Love,Optimism,Pessimism,Regret,Sadness,Shame,Shyness,Surprise,Trust,Neutral
Artist,,,,,,,,,,,,,,,,,,,,,
William Collins,2.500000,0.000000,0.00,0.0000,0.0000,0.000000,0.0000,0.000000,0.000000,1.000,...,0.600000,0.300000,0.0000,0.0000,0.000000,0.000000,0.0000,0.0000,0.1000,0.0
Maxfield Parrish,2.460000,0.154000,0.00,0.0770,0.0000,0.000000,0.0000,0.000000,0.154000,0.846,...,0.385000,0.385000,0.0000,0.0000,0.000000,0.000000,0.0000,0.0770,0.4620,0.0
Thomas Sully,2.400000,0.100000,0.00,0.1000,0.1000,0.000000,0.0000,0.000000,0.100000,0.500,...,0.000000,0.400000,0.0000,0.0000,0.000000,0.000000,0.0000,0.1000,0.6000,0.0
Ivan Shishkin,2.380000,0.130000,0.01,0.0900,0.0300,0.020000,0.0000,0.000000,0.090000,0.850,...,0.410000,0.340000,0.0200,0.0000,0.060000,0.000000,0.0200,0.0100,0.2700,0.0
Johan Christian Dahl,2.350000,0.000000,0.05,0.0500,0.0000,0.000000,0.0500,0.350000,0.100000,0.300,...,0.150000,0.100000,0.1000,0.0500,0.050000,0.000000,0.0000,0.1000,0.4500,0.0
Daniel Ridgway Knight,2.300000,0.000000,0.00,0.0000,0.0000,0.000000,0.0000,0.000000,0.100000,0.500,...,0.300000,0.200000,0.0000,0.0000,0.300000,0.000000,0.1000,0.0000,0.0000,0.0
Christoffer Wilhelm Eckersberg,2.270000,0.000000,0.00,0.0000,0.0910,0.000000,0.0000,0.000000,0.091000,0.182,...,0.182000,0.182000,0.0000,0.0000,0.000000,0.000000,0.0910,0.1820,0.3640,0.0
John Wilson Carmichael,2.200000,0.087000,0.00,0.1290,0.0000,0.087000,0.0455,0.087000,0.132500,0.606,...,0.041500,0.170500,0.0000,0.0000,0.000000,0.000000,0.0000,0.0000,0.3975,0.0
Nicolae Grigorescu,2.180000,0.182000,0.00,0.0910,0.0000,0.000000,0.0000,0.000000,0.091000,0.455,...,0.273000,0.273000,0.0000,0.0000,0.000000,0.000000,0.0000,0.0000,0.5450,0.0
Johann Anton de Peters,2.150000,0.150000,0.00,0.1000,0.0500,0.050000,0.0000,0.000000,0.250000,0.900,...,0.600000,0.300000,0.0000,0.0500,0.000000,0.000000,0.0500,0.1000,0.4000,0.0
Theodore Rousseau,2.150000,0.000000,0.00,0.0000,0.0000,0.000000,0.0000,0.000000,0.055500,0.889,...,0.050000,0.322000,0.0500,0.0500,0.100000,0.000000,0.0000,0.0000,0.1110,0.0
John William Godward,2.120000,0.032500,0.00,0.0841,0.0366,0.018900,0.0174,0.010600,0.062400,0.575,...,0.330200,0.228800,0.0091,0.0491,0.134700,0.000000,0.0075,0.0695,0.3447,0.0
Thomas Cole,2.100000,0.000000,0.00,0.2000,0.0000,0.000000,0.0000,0.000000,0.000000,0.900,...,0.000000,0.500000,0.0000,0.0000,0.000000,0.000000,0.0000,0.1000,0.3000,0.0
Theodore Chasseriau,2.093333,0.030333,0.00,0.0970,0.0970,0.030333,0.0000,0.030333,0.124333,0.391,...,0.451667,0.130333,0.0000,0.0000,0.030333,0.033333,0.0000,0.0000,0.3850,0.0
David Cox,2.090000,0.000000,0.00,0.2730,0.0910,0.000000,0.0000,0.000000,0.182000,0.455,...,0.000000,0.000000,0.0910,0.0000,0.091000,0.000000,0.0910,0.0000,0.3640,0.0

In [6]:
# CSV for average ratings for the style

styleEmotions = df.groupby(['Style']).mean()
# styleEmotions.to_csv('averageEmotionByStyle.csv')

In [39]:
# CSVs split by just styles

for i in range(len(styles)):
    frame = styleFrames[i]
    fileName = styles[i] + '.csv'
#     frame.to_csv(fileName)

In [11]:
# Testing by title keyword thing
test = styleFrames[0]
test = test[['Artist', 'Year', 'Title', 'Mean rating']]
test

,Artist,Year,Title,Mean rating
0,Robert Campin,1415,Triptych: The Two Thieves with the Empty Cross...,1.20
1,Masaccio,1422,St. Juvenal Triptych,1.06
2,Robert Campin,1424,Blessing Christ and Praying Virgin,1.60
3,Masaccio,1425,The Tribute Money,1.08
4,Masaccio,1426,St. Paul,1.45
...,...,...,...,...
304,Joachim Wtewael,1600,Martyrdom of St. Sebastian,1.70
312,Joachim Wtewael,1605,Kitchen Scene,0.80
315,Jan Provoost,1607,The Martyrdom of St. Catherine,1.60
322,Joachim Wtewael,1611,Perseus Rescuing Andromeda,1.83
355,Joachim Wtewael,1625,Adoration by the Shepherds,1.60

In [35]:
keywords = pd.read_csv('../ChristianityKeyWords.csv')
keywords = list(keywords['Keywords'])
# Making all keywords lowercase
keywords = [key.lower() for key in keywords]

C:\Users\lykas\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [38]:
def withChrist(c):
    if any(key in c['Title'] for key in keywords):
        return 'yes'
    else:
        return 'no'

In [40]:
# Creating new column for all the styles

for i in range(len(styles)):
    frame = styleFrames[i]
    # Making all titles lowercase
    frame['Title'] = [title.lower() for title in frame['Title']]
    frame['withChrist'] = frame.apply(withChrist, axis=1)
    fileName = styles[i] + '.csv'
#     frame.to_csv(fileName)

C:\Users\lykas\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\lykas\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys